@startuml

actor user
boundary ConsoleApplication
boundary ConsoleInputInterpreter
boundary Files
boundary InitCommandInterpreter
boundary VehicleSlots
boundary EnterVehicleCommandInterpreter
boundary EnterVehicleCommand
boundary ExitVehicleCommandInterpreter
boundary ExitVehicleCommand
boundary DefaultInterpreter
boundary ParkingSpace
boundary Vehicle
boundary VehicleTypeRepository

user -> ConsoleApplication: executes
ConsoleApplication -> ConsoleInputInterpreter: creates a chain of\ninterpreters of init,\nenter, exit and\ndefault interpreters
ConsoleApplication -> Files: read input file
group for each line
    ConsoleApplication -> ConsoleInputInterpreter: call chain of\ninterpreters
end

... InitCommandInterpreter is invoked ...

InitCommandInterpreter -> VehicleSlots: creates vehicle slots from input
InitCommandInterpreter -> ParkingSpace: Allocate vehicle slots
InitCommandInterpreter --> user: Shows success message
alt on failure
    InitCommandInterpreter --> user: Shows failure message
end

... EnterVehicleCommandInterpreter is invoked ...

EnterVehicleCommandInterpreter -> VehicleTypeRepository: fetches vehicle type given input
EnterVehicleCommandInterpreter -> Vehicle: creates vehicle given input
EnterVehicleCommandInterpreter -> EnterVehicleCommand: creates EnterVehicleCommand\nwith success and failure handlers
EnterVehicleCommandInterpreter -> EnterVehicleCommand: execute
EnterVehicleCommand --> user: Shows success message
alt on failure
    EnterVehicleCommand --> user: Shows failure message
end

... ExitVehicleCommandInterpreter is invoked ...

ExitVehicleCommandInterpreter -> VehicleTypeRepository: fetches vehicle type given input
ExitVehicleCommandInterpreter -> Vehicle: creates vehicle given input
ExitVehicleCommandInterpreter -> ExitVehicleCommand: creates ExitVehicleCommand\nwith success and failure handlers
ExitVehicleCommandInterpreter -> ExitVehicleCommand: execute
ExitVehicleCommand --> user: Shows success message
alt on failure
    ExitVehicleCommand --> user: Shows failure message
end

... DefaultInterpreter is invoked ...

DefaultInterpreter --> user: Shows default message

@enduml