@startuml

actor user
boundary ConsoleApplication
boundary ConsoleInputInterpreter
boundary Files
boundary InitCommandInterpreter
boundary VehicleSlots
boundary EnterVehicleCommandInterpreter
boundary EnterVehicleCommand
boundary ExitVehicleCommandInterpreter
boundary ExitVehicleCommand
boundary DefaultInterpreter
boundary ParkingSpace
boundary Vehicle
boundary ApplicationContext
boundary VehicleTypeRepository

user -> ConsoleApplication: executes
ConsoleApplication -> ConsoleInputInterpreter: creates a chain of interpreters of \ninit, enter, exit and default interpreters
ConsoleApplication -> Files: read input file
group for each line
    ConsoleApplication -> ConsoleInputInterpreter: call the
end

... InitCommandInterpreter is invoked ...

InitCommandInterpreter -> VehicleSlots: creates vehicle slots from input
InitCommandInterpreter -> ApplicationContext: gets parking space
alt not found
    InitCommandInterpreter -> ParkingSpace: creates a new parking space
    InitCommandInterpreter -> ApplicationContext: registers parking space
end
InitCommandInterpreter -> ParkingSpace: Allocate vehicle slots
alt on failure
    InitCommandInterpreter --> user: Shows failure message
end

... EnterVehicleCommandInterpreter is invoked ...

EnterVehicleCommandInterpreter -> VehicleTypeRepository: fetches vehicle type given input
EnterVehicleCommandInterpreter -> Vehicle: creates vehicle given input
EnterVehicleCommandInterpreter -> ApplicationContext: gets parking space
EnterVehicleCommandInterpreter -> EnterVehicleCommand: creates EnterVehicleCommand with success and failure handlers
EnterVehicleCommandInterpreter -> EnterVehicleCommand: execute
EnterVehicleCommand --> user: Shows success message
alt on failure
    EnterVehicleCommand --> user: Shows failure message
end

... ExitVehicleCommandInterpreter is invoked ...

ExitVehicleCommandInterpreter -> VehicleTypeRepository: fetches vehicle type given input
ExitVehicleCommandInterpreter -> Vehicle: creates vehicle given input
ExitVehicleCommandInterpreter -> ApplicationContext: gets parking space
ExitVehicleCommandInterpreter -> ExitVehicleCommand: creates ExitVehicleCommand with success and failure handlers
ExitVehicleCommandInterpreter -> ExitVehicleCommand: execute
ExitVehicleCommand --> user: Shows success message
alt on failure
    ExitVehicleCommand --> user: Shows failure message
end

... DefaultInterpreter is invoked ...

DefaultInterpreter --> user: Shows default message

@enduml