@startuml

class ConsoleApplication

class ApplicationContext {
    - constructor()
    + {static} getInstance(): ApplicationContext
    + register(Class type, Object bean)
    + getBean(Class type): Object
}

interface Interpreter {
    + supports(String line)
    + interpret(String line)
    + setNext(Interpreter interpreter)
}

class InitCommandInterpreter {
    + supports(String line)
    + interpret(String line)
    + setNext(Interpreter interpreter)
}

class EnterVehicleCommandInterpreter {
    + supports(String line)
    + interpret(String line)
    + setNext(Interpreter interpreter)
}

class ExitVehicleCommandInterpreter {
    + supports(String line)
    + interpret(String line)
    + setNext(Interpreter interpreter)
}

interface Command {
    + execute()
}

class EnterVehicleCommand {
    + constructor(ParkingSpace parkingSpace, Vehicle vehicle)
    + execute()
}

class ExitVehicleCommand {
    + constructor(ParkingSpace parkingSpace, Vehicle vehicle)
    + execute()
}


@enduml